### ISSUE TITLE
FTP Support

### ISSUE THREAD

**Issue by MormonBoy** [OffBroadway/flippydrive#1]
When watching the Macho Nacho Productions video about FlippyDrive, one major standout to me was the lack of FTP support on the device, especially since it has wifi capabilities built in. I think this would massively increase the value proposition of the device to not require disassembly each time you want to add games to the device.

**Comment by ChrisPVille** [comment]
The flippydrive already supports a network transfer protocol similar in concept to FTP using a custom application that can be run interactively or headless for things like RetroNAS.

The protocol currently supports things necessary to make the GameCube playable over wifi like large transfer windows and readahead. We're currently looking into opportunistic compression as well.

The disc protocol is extremely sensitive to latency so much of the design is geared around reducing latency but we're at the mercy of people's home network so wifi will probably remain experimental forever.  Ethernet on the other hand has even higher performance than the SD card when used on a fully wired network

**Comment by mahoneyt944** [comment]
@MormonBoy With a little care, you could probably use one of these cheap extensions to make the SD accessible from the outside.
![Sd](https://github.com/OffBroadway/flippydrive/assets/49591133/5d93b6c0-1b14-45cd-8f52-420f9ed6c8d7)
