### ISSUE TITLE
Make Sure Flippydrive is compatible with the upcoming MemCard PRO GC

### ISSUE THREAD

**Issue by genestrashcan** [OffBroadway/flippydrive#2]
When flippy drive is released make sure that it is compatible with the upcoming MemCard PRO GC.

The MemCard PRO GC is a custom memory card that can load individual game saves off emulated memory cards on an SD card and then some...

https://8bitmods.com/memcard-pro-gc-for-gamecube-smoke-black/

**Comment by mseeley** [comment]
Hello :). May I please ask related questions? I will direct them to a support contact if there is one available.

I believe the GameID with MemCard Pro GC is compatible when games are launched from Swiss. I am unsure if there are other compatibility issues.

Are there plans/challenges to support GameID+MemCard Pro GC integration when launching games from a patch bios? I am concerned about buying a Flippydrive then there being a hardware revision required to implement MemCard Pro GC compatibility.

Thank you for the information. :)

**Comment by ChrisPVille** [comment]
Memcard Pro support with Cubeboot is already in the tree and will be part of the next release when Trevor gets back from his trip.  In general, all of the cubeboot features run on the cube itself so there is no need to worry about any hardware revisions of the flippydrive with regards to software features.
