### ISSUE TITLE
 XGIII: Extreme G Racing non-clean mode crash via Swiss 

### ISSUE THREAD

**Issue by ChrisPVille** [OffBroadway/flippydrive#21]
After apploading from a previously setup fd 3, this command occurs `DI READ 0x156EBDA8 len 0x0 fd 1`, which triggers a bad command DI error due to the length being zero. This error causes the program to halt.

**Comment by trevor403** [comment]
Creating a fix that calls SEEK instead, this is what gcloader does

**Comment by ChrisPVille** [comment]
Fixed in our swiss patches, commit 6212869
