### ISSUE TITLE
Updated to 0.3.1 cant see screen

### ISSUE THREAD

**Issue by MaxPK** [OffBroadway/flippydrive#23]
Updated to recent version 0.3.1 and now booting through flippy does not show menues even though sound is herd perfectly fine.

https://youtube.com/shorts/YmW1-T2tlkQ?si=TTw6n9-fRr4VKX_X

**Comment by MaxPK** [comment]
https://youtube.com/shorts/YmW1-T2tlkQ?si=TTw6n9-fRr4VKX_X

**Comment by ChrisPVille** [comment]
This was new in 0.3.0 vs 0.3.1? I'll take a look and see if anything changes with video settings. Hearing sound means it's running, so it's got to be something that changes setting up video.

**Comment by MaxPK** [comment]
I can boot into swiss using the bootloader .dol

**Comment by MaxPK** [comment]
I found it. Ihad a feeling it was in the config.ini file put in andyea i had to change force progressive scan to a 0 instead of a 1

**Comment by ChrisPVille** [comment]
Great! We changed the config sample docs to have "safe" values so copy pasting would not have this issue in the future.
