### ISSUE TITLE
Compatibility for Panasonic Q

### ISSUE THREAD

**Issue by DrunkenMonk0001** [OffBroadway/flippydrive#4]
Is there any compatibility for the Panasonic Q? also does it include the old drive patchcodes like the older modchips like the viper, so region free booting discs too?

**Comment by masterquest91** [comment]
It's functionally compatible as it uses the same disc connector on the motherboard. The only challenge left is for the team to discover an optimal location where it can be mounted.

**Comment by ChrisPVille** [comment]
A mounting location has been identified, which required changes to the flex design.  The Q compatible flexes will be here in the next few days and we will be able to run a beta program for Q users to try out the new flex and mounting location in the next few weeks.

**Comment by ChrisPVille** [comment]
Tested working on Q with new flexes.  New mounting plates will iterate a few times based on user feedback.
