### ISSUE TITLE
An option to boot at startup a select dol file 

### ISSUE THREAD

**Issue by GeAd23** [OffBroadway/flippydrive#6]
1)
A option to configure what dol is booted at startup if I press on button or no button like a custom IPL.dol file. 
2)
what are the differences between Flippy Drive and Kunaigc ? Or there are non on feature side. 

Yours Sincerely

**Comment by ChrisPVille** [comment]
As of 0.2.1, a boot.dol on the SD card can be used to load any DOL file desired
0.2.9 adds the ability to load DOLs from within the cubeboot GUI itself

A future selection menu will be added to the bootloader to enable selection of specific DOLs, with file management utilities for storing DOLs on the internal flash
