### ISSUE TITLE
Bypassing logo with A during logo animation causes Cubeboot to present games as no disc

### ISSUE THREAD

**Issue by ChrisPVille** [OffBroadway/flippydrive#8]
Yep

**Comment by Czanron** [comment]
Not sure how much of an issue this really is but thought I'd report it. 

Holding A on boot bypasses Flippydrive completely until user selects Flippydrive game play option.

Waiting a few seconds until screen loads and GC animation starts then holding A appears to interrupt the Flippydrive boot causing games to appear as "no disc" in within cubeboot until reboot.

**Comment by trevor403** [comment]
This is due to the animation complete flag never getting set.... I used a different flag and it works in the next release
(>=alpha-rc35)

**Comment by ChrisPVille** [comment]
Fixed in 0.2.9
